sources:
###### Amazon SERPAPI ######
  - name: "marketplace1_price_listing"
    type: "oxylabs_amazon_pricing"
    enabled: true
    parameters:
      domain: "de"
      source: "amazon_pricing"
      category_label: "marketplace1_price_listing"
      gcs_bucket_name: "amazon-pricing-listing-raw-etrendo-prd"
      oxylabs_username_secret_name: "marketplace1-price-oxylabs-username"
      oxylabs_password_secret_name: "marketplace1-price-oxylabs-password"
      endpoint: "https://realtime.oxylabs.io/v1/queries"
      throttle_min_seconds: 0.05
      throttle_max_seconds: 0.2
  - name: "marketplace1_product_listing"
    type: "amazon_serpapi"
    enabled: true
    parameters:
      amazon_domain: "amazon.de"
      language: "en_GB"
      delivery_zip: "22085"
      node: "16075991"
      sort: "exact-aware-popularity-rank"
      category_label: "washing_machines"
      max_pages: 100
      gcs_bucket_name: "amazon-product-listing-raw-etrendo-prd"
  - name: "marketplace1_product_listing_coffee_machines"
    type: "amazon_serpapi"
    enabled: true
    parameters:
      amazon_domain: "amazon.de"
      language: "en_GB"
      delivery_zip: "22085"
      node: "13528250031"
      sort: "exact-aware-popularity-rank"
      category_label: "coffee_machines"
      max_pages: 100
      gcs_bucket_name: "amazon-product-listing-raw-etrendo-prd"
  - name: "marketplace1_product_listing_blenders_mixers"
    type: "amazon_serpapi"
    enabled: true
    parameters:
      amazon_domain: "amazon.de"
      language: "en_GB"
      delivery_zip: "22085"
      node: "3169561"
      sort: "exact-aware-popularity-rank"
      category_label: "blenders_mixers"
      max_pages: 100
      gcs_bucket_name: "amazon-product-listing-raw-etrendo-prd"
###### Otto ######
  - name: "marketplace2_product_details"
    type: "axesso_api"
    enabled: true
    parameters:
      axesso_endpoint: "https://api.axesso.de/ott/otto-lookup-product"
      category_label: "coffee_machines"
      gcs_bucket_name: "otto-product-details-raw-etrendo-prd"
      axesso_secret_name: "marketplace2-details-axesso-key"
  - name: "marketplace2_product_listing"
    type: "web_scraper"
    enabled: true
    parameters:
      category_url: "https://www.otto.de/haushalt/waschmaschinen/frontlader/"
      user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      category_label: "washing_machines"
      gcs_bucket_name: "otto-product-listing-raw-etrendo-prd"
  - name: "marketplace2_product_listing_coffee_machines"
    type: "web_scraper"
    enabled: true
    parameters:
      category_url: "https://www.otto.de/haushalt/kaffeemaschinen/"
      user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      category_label: "coffee_machines"
      gcs_bucket_name: "otto-product-listing-raw-etrendo-prd"
