sources:
###### Amazon SERPAPI ######
  - name: "marketplace1"
    type: "amazon_serpapi"
    enabled: true
    parameters:
      amazon_domain: "amazon.de"
      language: "en_GB"
      delivery_zip: "22085"
      node: "16075991"
      sort: "exact-aware-popularity-rank"
      category_label: "washing_machines"
      max_pages: 100
      gcs_bucket_name: "amazon-product-listing-raw-etrendo-prd"
  - name: "marketplace1_coffee_machines"
    type: "amazon_serpapi"
    enabled: true
    parameters:
      amazon_domain: "amazon.de"
      language: "en_GB"
      delivery_zip: "22085"
      node: "13528250031"
      sort: "exact-aware-popularity-rank"
      category_label: "coffee_machines"
      max_pages: 100
      gcs_bucket_name: "amazon-product-listing-raw-etrendo-prd"
  - name: "marketplace1_blenders_mixers"
    type: "amazon_serpapi"
    enabled: true
    parameters:
      amazon_domain: "amazon.de"
      language: "en_GB"
      delivery_zip: "22085"
      node: "3169561"
      sort: "exact-aware-popularity-rank"
      category_label: "blenders_mixers"
      max_pages: 100
      gcs_bucket_name: "amazon-product-listing-raw-etrendo-prd"
###### Otto ######
  - name: "marketplace2"
    type: "web_scraper"
    enabled: true
    parameters:
      category_url: "https://www.otto.de/haushalt/waschmaschinen/frontlader/"
      user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      category_label: "washing_machines"
      gcs_bucket_name: "otto-product-listing-raw-etrendo-prd"
  - name: "marketplace2"
    type: "web_scraper"
    enabled: true
    parameters:
      category_url: "https://www.https://www.otto.de/haushalt/kaffeemaschinen/"
      user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      category_label: "coffee_machines"
      gcs_bucket_name: "otto-product-listing-raw-etrendo-prd"