
bigquery:
  project_id: "etrendo-prd"
  dataset_id: "amazon_gold"
  table_id: "amazon_coffee_machines_snapshot_category_daily"
vertex_ai:
  project_id: "etrendo-prd"
  location: "us-central1"
  model_name: "gemini-2.0-flash-exp"
